
#define IDS_APP_TITLE			103

#define IDR_MAINFRAME			128
#define IDD_BATTERTRAY_DIALOG	102
#define IDD_ABOUTBOX			103
#define IDM_ABOUT				104
#define IDM_EXIT				105
#define IDI_BATTERTRAY        107
#define IDI_BATTERTRAYHALF    201
#define IDI_BATTERTRAYLOW     202
#define IDI_SMALL             104

#define IDC_BATTERTRAY			109
#define IDC_MYICON				2
#ifndef IDC_STATIC
#define IDC_STATIC				-1
#endif

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NO_MFC					130
#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_COMMAND_VALUE		32771
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		110
#endif
#endif

#define IDI_TRAYICON        101
#define IDD_SETTINGS        102
#define IDC_EDIT_URL        1001
#define IDC_EDIT_INTERVAL   1002
